export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const LIST_ADVISORS_REQUEST = 'LIST_ADVISORS_REQUEST'
export const LIST_ADVISORS_SUCCESS = 'LIST_ADVISORS_SUCCESS'

export const SET_ADVISOR = 'SET_ADVISOR'
export const ADD_ADVISOR_SUCCESS= 'ADD_ADVISOR_SUCCESS'
export const ADD_ADVISOR_ERROR = 'ADD_ADVISOR_ERROR'

export const LIST_NURSES_REQUEST = 'LIST_NURSES_REQUEST'
export const LIST_NURSES_SUCCESS = 'LIST_NURSES_SUCCESS'
export const LIST_NURSES_SUCCESS_NOT_FOUND = 'LIST_NURSES_SUCCESS_NOT_FOUND'

export const SET_NURSE = 'SET_NURSE'
export const ADD_NURSE_SUCCESS= 'ADD_NURSE_SUCCESS'
export const ADD_NURSE_ERROR = 'ADD_NURSE_ERROR'

export const LIST_BENEFICIALS_REQUEST = 'LIST_BENEFICIALS_REQUEST'
export const LIST_BENEFICIALS_SUCCESS_NOT_FOUND = 'LIST_BENEFICIALS_SUCCESS_NOT_FOUND'
export const LIST_BENEFICIALS_SUCCESS = 'LIST_BENEFICIALS_SUCCESS'

export const CHECK_UBUDEHE_REQUEST = 'CHECK_UBUDEHE_REQUEST'
export const CHECK_UBUDEHE_SUCCESS = 'CHECK_UBUDEHE_SUCCESS'
export const CHECK_UBUDEHE_SUCCESS_NOT_FOUND = 'CHECK_UBUDEHE_SUCCESS_NOT_FOUND'

export const ADD_BENEFICIAL_REQUEST = 'ADD_BENEFICIAL_REQUEST'
export const ADD_BENEFICIAL_SUCCESS = 'ADD_BENEFICIAL_SUCCESS'
export const ADD_BENEFICIAL_ERROR = 'ADD_BENEFICIAL_ERROR'

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST'
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

export const DONATE_REQUEST = 'DONATE_REQUEST'
export const DONATE_SUCCESS = 'DONATE_SUCCESS'
export const DONATE_STOCKOUT_MESSAGE = 'DONATE_STOCKOUT_MESSAGE'

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const READ_NOTIFICATION = 'READ_NOTIFICATION'
export const READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'

export const PRODUCT_CATEGORY_DETAILS = 'PRODUCT_CATEGORY_DETAILS'

export const ADD_GUARDIAN_REQUEST = 'ADD_GUARDIAN_REQUEST'
export const ADD_GUARDIAN_SUCCESS = 'ADD_GUARDIAN_SUCCESS'

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST'
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR'

export const STOCKIN_REQUEST = 'STOCKIN_REQUEST'
export const STOCKIN_SUCCESS = 'STOCKIN_SUCCESS'

export const LIST_APPOINTMENTS_REQUEST = 'LIST_APPOINTMENTS_REQUEST'
export const LIST_APPOINTMENTS_SUCCESS = 'LIST_APPOINTMENTS_SUCCESS'

export const GET_BENEFICIAL_APPOINTMENTS_REQUEST = 'GET_BENEFICIAL_APPOINTMENTS_REQUEST'
export const GET_BENEFICIAL_APPOINTMENTS_SUCCESS = 'GET_BENEFICIAL_APPOINTMENTS_SUCCESS'

export const ADD_BENEFICIAL_APPOINTMENT = 'ADD_BENEFICIAL_APPOINTMENT'
export const SET_SELECTED_BENEFICIAL_APPOINTMENTS = 'SET_SELECTED_BENEFICIAL_APPOINTMENTS'

export const CHANGE_APPOINTMENT_STATUS = 'CHANGE_APPOINTMENT_STATUS'

export const REPORT_BENEFICIAL_USE_ABUSE_SUCCESS = 'REPORT_BENEFICIAL_USE_ABUSE_SUCCESS'